# .github/workflows/circle.yml

# Workflow name
name: 'CircleCI'

# Event for the workflow
on: push

# List of jobs
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to CircleCI
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
