# .github/workflows/circle.yml

# Workflow name
name: 'CircleCI'

# Event for the workflow
on:
  pull_request:
    types: [opened, reopened, synchronize, assigned, edited]

# List of jobs
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to CircleCI
        id: <customize id>
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
